int prunik(const int A[],int a,const int B[],int b,int C[]);

int srozdil(const int A[],int a,const int B[],int b,int C[]);

int sjednoceni(const int A[],int a,const int B[],int b,int C[]);

int rozdil(const int A[],int a,const int B[],int b,int C[]);

void vypis(const int A[],int a,int n);

const int A[]={1,5,6,9,0,8,3};

#define aa (sizeof A/sizeof *A)

const int B[]={9,2,4,3,6,7};

#define bb (sizeof B/sizeof *B)
