const Slovnik CA[]={{"pamet","memory"},{"pamet","storage"},{"vypocet","calculation"},{"vypocet","computation"},
                    {"pocitac","computer"},{"pocitac","counter"},{"hracka","toy"},{"instrukce"," instruction"},{"hracka","plaything"},
                    {"instrukce","instruction"},{"chyba","mistake"},{"chyba","error"},{"chyba","fault"},{"chyba","flaw"},{"chyba","defect"},
                    {"pocet","number"},{"pocet","number"},{"pocet","count"},{"pocet","quantity"},{"disk","disk"},{"disk","disc"},{"disk","disk"},
                    {"polovina","half"},{"polovina","middle"},{"polovina","midpoint"},{"polovina","center"},{"pamet","storage"},
                    {"slozitost","complicatedness"},{"slozitost","complexity"},{"slozitost","intricacy"},
                    {"pouziti","use"},{"pouziti","application"},{"pouziti","employment"},{"pouziti","usage"},
                    {"pocet","number"},{"pocet","number"},{"pocet","count"},{"pocet","quantity"},{"disk","disk"},{"disk","disc"},{"disk","disk"},
                    {"cyklus","loop"},{"cyklus","cycle"},{"cyklus","series"},{"cyklus","course"},
                    {"prikaz","order"},{"prikaz","command"},{"slovo","word"},{"promenna","variable"},
                    {"frekvence","frequency"},{"frekvence","rate"},{"cetnost","frequency"}};

#define CAPOCET (sizeof CA/sizeof *CA)
